Questions = [
	"Care e filozofia vietii tale?",
	"Care e un lucru pe care l-ai schimba la tine?",
	"Esti o persoana religioasa sau spirituala?",
	"Te consideri o persoana extrovertita sau introvertita?",
	"De care parine esti mai apropiat si de ce?",
	"Care a fost cea mai buna perioada din viata ta?",
	"Care a fost cea mai nasoala perioada din viata ta?",
	"Ce faci acum e ce ti-ai dorit dintotdeauna sa faci?",
	"Ce te face sa te simti indeplinit(a)?",
	"Care e cartea/filmul tau preferat?",
	"Ce conteaza mai mult: aspectul sau personalitatea?",
	"Ai imparti datele de la un cont cu altcineva?",
	"Ce fel de parinte crezi ca vei fi?",
	"Care e o persoana cu care poti vorbi despre orice?",
	"De obicei ramai prieten(a) cu fostii/fostele tale?",
	"Ai pierdut vreodata pe cineva apropia?",
	"Cand nu te simti bine, preferi sa stai singur(a) sau cu cineva care te face sa te simti mai bine?",
	"Cum arata weekendul tau ideal?",
	"Crezi ca e posibil sa avem prieteni cei mai buni de sex opus?",
	"Judeci o carte dupa coperta?",
	"Esti o persoana impulsiva sau care se supara usor?",
	"Ai frant vreodata inima cuiva?",
	"Te-ai muta pentru o persoana iubita?",
	"Ai scris vreodata un jurnal?",
	"Pentru ce esti cel mai recunoscator?",
	"Ti-ar placea sa fii faimos/faimoasa? In ce fel?",
	"Iti faci vreodata un discurs pentru ce urmeaza sa zici la telefon sau sa zici cuiva?",
	"Crezi in a doua sansa?",
	"Cum arata o zi perfecta pentru tine?",
	"Ce iti spune intuitia despre cum o sa mori?",
	"Ia un cronometru. Povesteste viata ta in 4 minute. Go!",
	"La ce tii cel mai mult intr-o prietenie?",
	"Care e cea mai indragita memorie a ta?",
	"Ce nu inteleg oamenii despre tine de obicei?",
	"Cum arata o vacanta perfecta pentru tine?",
	"Ce ai invatat din ultima ta relatie?",
	"Ce crezi despre Tinder si online dating?",
	"Ce ti-ai propus sa faci anul asta?",
	"Cand ai avut cel mai puternic puls de adrenalina?",
	"Care a fost cel mai nebun lucru pe care l-ai facut? Ai face asta din nou?",
	"Daca un duh ti-ar oferi 3 dorinte, ce ti-ai dori?",
	"Care e cel mai mare regret al tau?",
	"La ce te gandesti cand esti singur(a)?",
	"Ce voiai sa fii cand erai mic(a)?",
	"Care a fost cea mai mare greseala a ta si ce ai invatat din ea?",
	"Care e locul tau preferat in care iti place sa mergi?",
	"Care sunt piesele tale preferate?",
	"Ce calitati admiri la parintii tai?",
	"Descrie-ti prietenul cel mai bun (sau prietena cea mai buna).",
	"Care e hobby-ul tau preferat pe care il faci singur(a)?",
	"Care e hobby-ul tau preferat?",
	"Care e un lucru fara de care nu poti supravietui o zi?",
	"Care a fost cel mai spontan lucru facut recent?",
	"Care a fost cea mai nebuna chestie pe care ai facut-o pentru dragoste?",
	"Ce ti se pare foarte enervant?",
	"De ce realizare a ta esti cel mai mandru(a)?",
	"Care e un vis care inca nu ti s-a indeplinit?",
	"De ce ti-e cel mai frica?",
	"Care sunt 3 lucruri pe care le apreciezi la oameni?",
	"Care sunt cele mai apropiate 3 persoane de tine?",
	"Care a fost cel mai greu lucru peste care ai trecut?",
	"Daca ai putea locui oriunde in lume, unde ai locui?",
	"Ce lucru interesant ti s-a intamplat anul asta?",
	"Ce lucru nu iti place la lumea din ziua de azi?",
	"Esti mai apropiat de mama sau de tatal tau?",
	"Daca ai schimba un lucru la tine, ce ai schimba?",
	"Daca ai schimba un lucru la lume, ce ai schimba?",
	"Cine a fost/este profesorul tau preferat si de ce?",
	"Cine a fost cel mai nasol profesor pe care l-ai avut?",
	"Care e cel mai ciudat lucru la tine?",
	"Care e cel mai magic lucru la tine?",
	"Cum te-ar descrie pretenul tau cel mai bun (sau prietena)?",
	"Cine e personajul tau istoric preferat?",
	"Ce te-a facut sa alegi facultatea/liceul pe care l-ai facut?",
	"Daca ai putea sa iti spui tie in trecut ceva, ce ti-ai spune?",
	"Fara de ce mancare nu ai putea sa traiesti?",
	"Caini sau pisici?",
	"Ai fost vreodata arestat? Cat de aproape ai fost?",
	"Care a fost cea mai tare zi de nastere?",
	"Ce ti-ai dori sa stii sa faci dar nu stii?",
	"Unde ai vrea sa mergi si nu ai fost niciodata?",
	"Care a fost ultima carte citita si cand ai citit-o?",
	"Cum te tii la curent cu ce se intampla in lume?",
	"Ce ti-ai propus sa faci in urmatorii 5 ani?",
	"Daca ai putea face orice fara consecinte, ce ai face?",
	"Cine e eroul tau preferat?",
	"Care e cel mai mare risc pe care ti l-ai asumat vreodata?",
	"Crezi ca e un motiv pentru ca existam?",
	"Daca raiul exista si ai muri maine, ai fi primit(a)?",
	"Crezi in destin?",
	"Cum crezi ca te vad cei din jur?",
	"Daca ai putea sa stergi din trecut ceva ce ai facut, ce ai sterge?",
	"Ce piesa te face fericit(a)?",
	"Daca ai putea trai viata altcuiva, pe cine ai alege?",
	"Ce piesa te face trist(a)?",
	"Daca ar exista vieti anterioare, ce/cine ai fost intr-o viata anterioara?",
	"Ai vazut vreodata ceva ce nu iti explici?",
	"Care a fost cel mai ciudat vis pe care l-ai avut?",
	"Ce te face sa te simti inconfortabil?",
	"Exista vreo activitate sau vreun loc care te calmeaza cand ai o zi proasta?",
	"Ce gand sau idee te face sa te simti nelinistit(a)?",
	"Ce scena dintr-un film a avut un impact emotional puternic asupra ta?",
	"Unde mergi cand vrei sa fii singur(a)?",
	"Ce te face sa te simti ca ai nevoie de spatiu sau sa fii singur(a)?",
	"Care a fost cel mai mare esec al tau? Dar cel mai mare succes?",
	"Ce ignori dar stii ca nu ar trebui sa ignori?",
	"Care e cea mai gogonata minciuna pe care ai spus-o?",
	"Ai secrete?",
	"Ai avut mereu aceeasi orientare politica?",
	"Care e scopul vietii tale?",
	"Ai fost vreodata indragostit(a)?",
	"Ai avut vreodata inima franta?",
	"Cand ai plans ultima oara si de ce?",
	"Ai plans vreodata de fericire?",
	"Cand ai ranit pe cineva cel mai tare si de ce?",
	"Daca viata ta ar fi o carte sau un film, ce titlu ar avea?",
	"Cand ti-ai cauzat singur(a) cele mai multe daune?",
	"Ce faci pentru persoanele pe care le iubesti cel mai mult?",
	"Pentru tine, 'acasa' e un loc sau un sentiment?",
	"Te-ai indoit vreodata de sanatatea ta mintala?",
	"Care e memoria ta preferata din copilarie?",
	"Ai vise sau cosmaruri recurente?",
	"Crezi in viata pe alte planete?",
	"Ai vazut sau interactionat vreodata cu extraterestri?",
	"Crezi in fantome si spirite?",
	"Ai vazut sau interactionat vreodata cu fantome?",
	"Crezi in alte dimensiuni sau universuri paralele?",
	"Ce inseamna pentru tine arta?",
	"Crezi ca se intampla ceva dupa moarte?",
	"Ti-ar placea sa stii data exacta cand vei muri?",
	"Ti-ar placea sa fii nemuritor/nemuritoare?",
	"Alege intre a iubi si a fi iubit.",
	"Cum ai defini frumusetea??",
	"De unde crezi ca vine fericirea?",
	"Te consideri perfect liber/a?",
	"Ce parere ai despre deja-vu?",
	"Care e bancul tau idiot preferat?",
	"Daca ai putea avea orice animal de pe pamant animalul tau de companie, care ar fi?",
	"Crezi ca barbatii sunt mai rationali din fire, iar femeile mai emotive?",
	"Cum a fost primul tau sarut?",
	"S-a intamplat vreodata ca durerea cuiva sa iti aduca satisfactie? Fii sincer/a",
  "Care e punctul tau forte (in afara locului de munca/scolii)?",
	"Iti cunosti bine starea de sanatate actuala?",
	"Care e cea mai supranaturala sau paranormala frica a ta?",
	"Daca ai primi acum, pe loc, un cec de 25.000 de lei, cum l-ai folosi?",
	"Ti s-a intamplat sa ai probleme sa adormi?",
	"Crezi in materialism si/sau spiritualitate?",
	"Daca ai fi obligat/a sa alegi o religie, care ar fi aceea?",
	"Care este cel mai romantic si plin de entuziasm gest pe care l-ai facut cuiva vreodata?",
	"Care a fost cea mai mare aventura a ta de pana acum?",
	"Care e mantra (rutina) ta de zi cu zi?",
	"Care este citatul care ti se potriveste cel mai bine?",
	"Care este anti-motto-ul tau?",
	"Ce trasatura invidiezi la altii?",
	"Ce capacitati ti-ai dori sa fi avut?",
	"Cum ti-ai dori ca ceilalti sa isi aminteasca de tine?",
	"Cum ti-ai sumariza sensul vietii?",
	"Ce show-uri iti plac?",
	"Cat de popular esti si ce te face popular?",
	"Sporturi?",
	"Ai obiceiul sa vii mai devreme sau sa intarzii?",
	"Care e bautura ta preferata?",
	"Unde ti-ai fi dorit sa te nasti?",
	"Ce melodii ai memorat in totalitate pana acum?",
	"Unde te-ai clasa pe o scara de la 1 la 10?",
	"La ce job nu te-ai descurca deloc?",
	"Pe ce website intri cel mai des?",
	"Cum ar arata camera perfecta pentru tine?",
	"Pana la ce varsta iti doresti sa traiesti?",
	"Ce activitate crezi ca iti consuma mult prea mult timp?",
    "Cat de diferita era viata ta anul trecut?",
	"Care este genul tau favorit de carte sau film?",
	"Care este cel mai indepartat loc de casa ta in care ai fost?",
	"Ce trend ti-ai dori sa revina?",
	"Ce te tine treaz noaptea?",
	"Care e minciuna pe care o spui cel mai des?",
	"Care e un lucru pe care regreti ca nu l-ai facut?",
	"Pe ce anume esti cel mai nesigur?",
	"Care e cel mai ilegal lucru pe care l-ai facut pana acum?",
  	"Care este animalul tau salbatic preferat?",
	"Daca ai fi o pasare, ce pasare ca ai fi?",
	"Ce parere ai despre LGBT?",
	"Cate si ce limbi straine stii?",
	"Ce tip de personalitate ai?",
	"Ce credeti unul despre celalalt? Fiti onesti!",
	"Care este cel mai frumos cadou pe care l-ai oferit cuiva pana acum?",
	"Este ceva ce nu mananci absolut deloc?",
	"S-a intamplat ceva care sa te surprinda cumva azi?",
	"Care e cel mai bun sfat pe care l-ai primit vreodata?",
	"Cum erai cand erai mic(a)?",
	"Cum arata o zi tipica din viata ta?",
	"Care este lucrul pentru care esti cel mai cunoscut printre prieteni?",
	"Ce lucru sau activitate ti-ar placea sa impartasesti cu cineva?"
]

RelationshipQuestions = [
	"Care e cel mai jenant lucru care ti s-a intamplat in publoc?",
	"Sincer, care e ultimul lucru pe care l-ai cautat pe telefon?",
	"Ce defect poti accepta la un partener.",
	"Ce defect nu poti accepta la un partener.",
	"Care a fost cea mai lunga relatie a ta?",
	"De ce s-a terminat ultima ta relatie?",
	"Care e un 'deal breaker' pentru o relatie cu tine?",
	"Ai putea sa te impaci cu cineva care te-a inselat?",
	"Ce parere ai despre casatorie?",
	"Ce ai face daca parintilor tai nu le-ar placea de partenerul tau?",
	"Ce conteaza mai mult: banii sau dragostea?",
	"Ce orientare sexuala ai? Te-ai indoit vreodata",
	"Ai inselat vreodata pe cineva?",
	"Spune-ti-va un secret unul celuilalt (si promiteti ca nu spuneti nimanui!)",
	"Ce inseamna pentru cine 'wife/husband material'?",
	"Care e cel mai romantic lucru pe care l-ai facut?",
	"Ce ai face daca ai fi de sexul opus pentru o zi?",
	"Ce roluri joaca dragostea si afectiunea in viata ta?",
	"Cand ai plans ultima oara in fata cuiva?",
	"Spuneti un lucru care va place la celalalt!",
	"Crezi ca nu trebuie facute glume despre unele subiecte?"
]

SexQuestions = [
	"Ai facut vreodata poze cu tine gol/goala?",
	"Ai trimis vreodata 'nudes' cuiva?",
	"Ce parere ai despre pornografie?",
	"Ce parere ai despre hentai?",
	"Cati parteneri ai avut?",
	"Ai vreo jucarie sexuala?"
]