Questions = [
	"What’s your philosophy in life?",
	"What’s the one thing you would like to change about yourself?",
	"Are you religious or spiritual?",
	"Do you consider yourself an introvert or an extrovert?",
	"Which parent are you closer to and why?",
	"What was the best phase in your life?",
	"What was the worst phase in your life?",
	"Is what you’re doing now what you always wanted to do growing up?",
	"What makes you feel accomplished?",
	"What’s your favorite book/movie of all time and why did it speak to you so much?",
	"Are you more into looks or brains?",
	"How do you feel about sharing your password with someone?",
	"What kind of parent do you think you will be?",
	"Who is that one person you can talk to about just anything?",
	"Do you usually stay friends with your exes?",
	"Have you ever lost someone close to you?",
	"If you are in a bad mood, do you prefer to be left alone or have someone to cheer you up?",
	"What’s an ideal weekend for you?",
	"What do you think of best friends of the opposite sex?",
	"Do you judge a book by its cover?",
	"Are you confrontational?",
	"Have you ever broken someone’s heart?",
	"Would you relocate for love?",
	"Did you ever write a journal?",
	"What are you most thankful for?",
	"Would you like to be famous? In what way?",
	"Before making a telephone call, do you ever rehearse what you are going to say?",
	"Do you believe in second chances?",
	"What would be a perfect day for you?",
	"Do you have a secret hunch about how you will die?",
	"Get a cronometer. Tell your life story in 4 minutes. Go!",
	"What do you value most in a friendship?",
	"What is your most treasured memory?",
	"What’s the one thing that people always misunderstand about you?",
	"What is your idea of a perfect vacation?",
	"What did your past relationship teach you?",
	"What are your thoughts on online dating or tinder?",
	"What’s on your bucket list this year?",
	"When have you felt your biggest adrenaline rush?",
	"What is the craziest thing you’ve ever done and would you do it again?",
	"If a genie granted you 3 wishes right now, what would you wish for?",
	"What’s your biggest regret in life?",
	"What do you think about when you’re by yourself?",
	"What did you want to be when you were younger?",
	"What’s been your biggest mistake so far in life and what did you learn from it?",
	"Where is your favorite place in the entire world to go?",
	"What are some of your favorite songs?",
	"What qualities do you admire about your parents?",
	"How would you describe your best friend?",
	"What’s your favorite hobby to do alone?",
	"What’s your favorite hobby?",
	"What’s something you can’t go a day without doing?",
	"What’s the most spontaneous thing you’ve done lately?",
	"What’s the craziest thing you’ve ever done for love?",
	"What’s something you find annoying?",
	"What accomplishment are you most proud of?",
	"What is one dream you have yet to accomplish?",
	"What is your greatest fear?",
	"What are three things you value most about a person?",
	"Who are 3 people you are closest with?",
	"What is the greatest struggle you’ve overcome?",
	"If you could live anywhere in the world where would it be?",
	"What’s the most exciting thing that’s happened this past year?",
	"What’s one thing that bothers you most about the world today?",
	"Who are you closer with your mom or your dad?",
	"If you could change one thing about yourself what would it be?",
	"If you could change one thing about the world what would it be?",
	"Who was your favorite teacher and why?",
	"Who was your least favorite teacher and why?",
	"What is the weirdest thing about you?",
	"What would your best friend say is your best quality?",
	"Who is your favorite historical figure?",
	"What made you choose the college you went to?",
	"If you could tell your former self one thing right now what would it be?",
	"What food could you not live without?",
	"Dogs or Cats?",
	"What’s closest you’ve ever come to being arrested?",
	"What was your best birthday?",
	"What’s one thing you wish you knew how to do?",
	"Where’s one place you’d like to go that you haven’t been?",
	"What was the last book you read? And When?",
	"Where do you usually get your news?",
	"What are some of your own personal goals in the next 5 years?",
	"If you could get away with anything, what would you do?",
	"Who is your greatest hero?",
	"What’s the greatest risk you’ve ever taken?",
	"Do you believe there's a reason for our existence?",
	"If heaven is real and you died tomorrow, would you get in?",
	"Do you believe in fate?",
	"How do you think people see you?",
	"If you had the ability to erase something that you did in the past, what would it be?",
	"What song makes you unconditionally happy?",
	"If you could have anybody else’s life, who’s would you take?",
	"What song makes you unconditionally sad?",
	"If past lives are real, what was yours?",
	"Have you ever seen something you can’t explain?",
	"What is the strangest dream you’ve ever had?",
	"Is there something currently going on out there that you find deeply unsettling?",
	"Is there an activity that calms you? A place or a thing that makes you feel at ease?",
	"What makes you feel uneasy?",
	"What scene in a movie has evoked the most feelings out of you?",
	"What do you do or where do you go when you need to be alone?",
	"What makes you feel like you need to be alone?",
	"Where have you felt the most failure? The most success?",
	"Tell me about the facts or harsh truths you choose to ignore but know you shouldn’t.",
	"What is the biggest lie you ever told?",
	"Do you have secrets?",
	"Have you always had the same political beliefs?",
	"Where do you find meaning in your life?",
	"Have you ever been in love?",
	"Have you ever had your heart broken?",
	"Why did you cry the last time you did so?",
	"Have you ever cried tears of joy?",
	"What did you do when you hurt someone the most?",
	"If your life was a movie or a book what would be the title to it?",
	"When have you caused the most harm to yourself?",
	"Think about the people you love the most in your life, what do you do for them?",
	"Is home for you a place or a feeling?",
	"Have you ever questioned your sanity and why?",
	"What is your favorite childhood memory?",
	"Do you have any recurring dreams or nightmares?",
	"Do you believe in extraterrestrial life?",
	"Have you ever had an encounter with aliens?",
	"Do you believe in ghosts and spirits?",
	"Have you ever had an encounter with a ghost or a spirit?",
	"Do you believe in other dimensions and parallel universes?",
	"How do you define art?",
	"What do you think happens after death, if anything?",
	"If you could be given the date of your death would you want to know it?",
	"Presented with the opportunity to be immortal would you take it?",
	"Would you rather be loved or love?",
	"How do you define beauty?",
	"Where does happiness come from?",
	"Do you believe yourself to be truly free?",
	"What do you think about deja-vu's?",
	"What's your favorite stupid joke?",
	"If you could have any animal in the world as a pet, what would it be and why?",
	"Do you think that men are more rational and women are more emotional?",
	"What was your first kiss like?",
	"Has another’s pain ever given you joy? Be totally honest.",
	"What's your biggest strength outside of your workplace?",
	"Are you health conscious?",
	"What's your biggest supernatural or paranormal fear?",
	"If you got a free cheque for $5,000 right now, how would you use it?",
	"Have you ever been unable to sleep?",
	"Do you believe in materialism or spirituality?",
	"If you were forced to pick one religion, which one would it be?",
	"What is the most romantic and loving thing you have ever done for somebody?",
	"What is the most adventurous thing you have ever done in your life?",
	"What’s your day-to-day mantra?",
	"What quote resonates with you more than any other?",
	"What’s your anti-motto?",
	"What trait do you envy in others?",
	"What skill do you wish you had?",
	"How do you wish to be remembered?",
	"How would you summarize your life purpose?",
	"What shows are you into?",
	"hat’s your claim to fame?",
	"How often do you play sports?",
	"Are you usually early or late?",
	"What’s your favorite drink?",
	"Where would you rather be from?",
	"What songs have you completely memorized?",
	"What would you rate 10 / 10?",
	"What job would you be terrible at?",
	"What website do you visit most often?",
	"What would your perfect room look like?",
	"What age do you want to live to?",
	"What takes up too much of your time?",
	"How different was your life one year ago?",
	"What’s your favorite genre of book or movie?",
	"What’s the farthest you’ve ever been from home?",
	"What trend do you hope comes back?",
	"What keeps you up at night?",
	"What lie do you tell most often?",
	"What do you regret not doing?",
	"What are you most insecure about?",
	"What’s the most illegal thing you’ve done?",
	"What's your favorite wild animal?",
	"If you were a bird, what bird would you be?",
	"What's your opinion on LGBT?",
	"What languages do you speak?",
	"What's your personality type?",
	"What do you think about eachother? Be totally honest.",
	"What’s the best present you ever gave someone?",
	"Is there anything you don’t eat?",
	"Did anything surprising happen today?",
	"What’s the best advice anyone ever gave you?",
	"What were you like as a kid?",
	"What does a typical day look like for you?",
	"Among your friends, what's the thing you are known for?",
	"What is something you wish you could share with someone?"
]

RelationshipQuestions = [
	"What’s the most embarrassing thing that’s ever happened to you in public?",
	"What’s the last thing you searched on your phone?",
	"Name the one bad quality you wouldn’t mind in a partner.",
	"Name the one worst quality you cannot tolerate in a partner.",
	"What was your longest relationship?",
	"Why did your last relationship end?",
	"What is a relationship deal breaker for you?",
	"Would you ever take back someone who cheated?",
	"When do you think a person is ready for marriage?",
	"What would you do if your parents didn’t like your partner?",
	"What matters more, money or love?",
	"What's your sexual orientation? Have you ever had doubts?",
	"Have you ever cheated on someone?",
	"What's a secret of yours? (Don't tell anyone else, promise it!)",
	"What does wife / husband material mean to you?",
	"What's the most romantic thing you've ever done?",
	"If you were the opposite sex for one day, what would you do?",
	"What roles do love and affection play in your life?",
	"When did you last cry in front of another person?",
	"What's one thing you like about eachother?",
	"What is too serious to be joked about?"
]

SexQuestions = [
	"Have you ever taken nudes of yourself?",
	"Have you ever sent nudes to someone?",
	"What do you think of porn?",
	"What do you think of hentai?",
	"How many partners have you had?",
	"Do you own a sex toy?"
]